version: '3'

services:
  db:
    image: "postgres"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: blog
      POSTGRES_USER: mybloguser
      POSTGRES_PASSWORD: mypass
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db